<?php


return [
    'data' => [
        0 => [
            'Sr No.' => 1,
            'First Name' => 'Himanshu',
            'Last Name' => 'Sikka',
            'Email ID' => 'D21MCA16002@cuchd.in',
            'Student Registration Number' => 'd21mca16002',
            'USERNAME' => 'd21mca16002',
            'PASSWORD' => 'cumca148',
        ],
        1 => [
            'Sr No.' => 2,
            'First Name' => 'Naina',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16003@cuchd.in',
            'Student Registration Number' => 'd21mca16003',
            'USERNAME' => 'd21mca16003',
            'PASSWORD' => 'cumca116',
        ],
        2 => [
            'Sr No.' => 3,
            'First Name' => 'Sonu',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16004@cuchd.in',
            'Student Registration Number' => 'd21mca16004',
            'USERNAME' => 'd21mca16004',
            'PASSWORD' => 'cumca137',
        ],
        3 => [
            'Sr No.' => 4,
            'First Name' => 'Vanika',
            'Last Name' => 'Kamboj',
            'Email ID' => 'D21MCA16005@cuchd.in',
            'Student Registration Number' => 'd21mca16005',
            'USERNAME' => 'd21mca16005',
            'PASSWORD' => 'cumca126',
        ],
        4 => [
            'Sr No.' => 5,
            'First Name' => 'Ravi',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16006@cuchd.in',
            'Student Registration Number' => 'd21mca16006',
            'USERNAME' => 'd21mca16006',
            'PASSWORD' => 'cumca149',
        ],
        5 => [
            'Sr No.' => 6,
            'First Name' => 'Vrinda',
            'Last Name' => 'Khurana',
            'Email ID' => 'D21MCA16007@cuchd.in',
            'Student Registration Number' => 'd21mca16007',
            'USERNAME' => 'd21mca16007',
            'PASSWORD' => 'cumca145',
        ],
        6 => [
            'Sr No.' => 7,
            'First Name' => 'Debabrata',
            'Last Name' => 'Sarkar',
            'Email ID' => 'D21MCA16008@cuchd.in',
            'Student Registration Number' => 'd21mca16008',
            'USERNAME' => 'd21mca16008',
            'PASSWORD' => 'cumca111',
        ],
        7 => [
            'Sr No.' => 8,
            'First Name' => 'Suraj',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16009@cuchd.in',
            'Student Registration Number' => 'd21mca16009',
            'USERNAME' => 'd21mca16009',
            'PASSWORD' => 'cumca152',
        ],
        8 => [
            'Sr No.' => 9,
            'First Name' => 'Kulbir',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16010@cuchd.in',
            'Student Registration Number' => 'd21mca16010',
            'USERNAME' => 'd21mca16010',
            'PASSWORD' => 'cumca139',
        ],
        9 => [
            'Sr No.' => 10,
            'First Name' => 'Anjali',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16011@cuchd.in',
            'Student Registration Number' => 'd21mca16011',
            'USERNAME' => 'd21mca16011',
            'PASSWORD' => 'cumca136',
        ],
        10 => [
            'Sr No.' => 11,
            'First Name' => 'Samanway',
            'Last Name' => 'Koley',
            'Email ID' => 'D21MCA16012@cuchd.in',
            'Student Registration Number' => 'd21mca16012',
            'USERNAME' => 'd21mca16012',
            'PASSWORD' => 'cumca143',
        ],
        11 => [
            'Sr No.' => 12,
            'First Name' => 'Jaskaranbir',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16013@cuchd.in',
            'Student Registration Number' => 'd21mca16013',
            'USERNAME' => 'd21mca16013',
            'PASSWORD' => 'cumca134',
        ],
        12 => [
            'Sr No.' => 13,
            'First Name' => 'Suniti',
            'Last Name' => 'Papneja',
            'Email ID' => 'D21MCA16014@cuchd.in',
            'Student Registration Number' => 'd21mca16014',
            'USERNAME' => 'd21mca16014',
            'PASSWORD' => 'cumca107',
        ],
        13 => [
            'Sr No.' => 14,
            'First Name' => 'Harpreet',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16015@cuchd.in',
            'Student Registration Number' => 'd21mca16015',
            'USERNAME' => 'd21mca16015',
            'PASSWORD' => 'cumca105',
        ],
        14 => [
            'Sr No.' => 15,
            'First Name' => 'Abhilasha',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16016@cuchd.in',
            'Student Registration Number' => 'd21mca16016',
            'USERNAME' => 'd21mca16016',
            'PASSWORD' => 'cumca129',
        ],
        15 => [
            'Sr No.' => 16,
            'First Name' => 'Kishan',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16017@cuchd.in',
            'Student Registration Number' => 'd21mca16017',
            'USERNAME' => 'd21mca16017',
            'PASSWORD' => 'cumca102',
        ],
        16 => [
            'Sr No.' => 17,
            'First Name' => 'Ravi',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16018@cuchd.in',
            'Student Registration Number' => 'd21mca16018',
            'USERNAME' => 'd21mca16018',
            'PASSWORD' => 'cumca127',
        ],
        17 => [
            'Sr No.' => 18,
            'First Name' => 'Sheetal',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16019@cuchd.in',
            'Student Registration Number' => 'd21mca16019',
            'USERNAME' => 'd21mca16019',
            'PASSWORD' => 'cumca117',
        ],
        18 => [
            'Sr No.' => 19,
            'First Name' => 'Tushar',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16020@cuchd.in',
            'Student Registration Number' => 'd21mca16020',
            'USERNAME' => 'd21mca16020',
            'PASSWORD' => 'cumca110',
        ],
        19 => [
            'Sr No.' => 20,
            'First Name' => 'Ruchita',
            'Last Name' => 'Dave',
            'Email ID' => 'D21MCA16021@cuchd.in',
            'Student Registration Number' => 'd21mca16021',
            'USERNAME' => 'd21mca16021',
            'PASSWORD' => 'cumca140',
        ],
        20 => [
            'Sr No.' => 21,
            'First Name' => 'Arushi',
            'Last Name' => 'Dutt',
            'Email ID' => 'D21MCA16022@cuchd.in',
            'Student Registration Number' => 'd21mca16022',
            'USERNAME' => 'd21mca16022',
            'PASSWORD' => 'cumca130',
        ],
        21 => [
            'Sr No.' => 22,
            'First Name' => 'Avinash',
            'Last Name' => 'Pandey',
            'Email ID' => 'D21MCA16023@cuchd.in',
            'Student Registration Number' => 'd21mca16023',
            'USERNAME' => 'd21mca16023',
            'PASSWORD' => 'cumca146',
        ],
        22 => [
            'Sr No.' => 23,
            'First Name' => 'Gurpreet',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16024@cuchd.in',
            'Student Registration Number' => 'd21mca16024',
            'USERNAME' => 'd21mca16024',
            'PASSWORD' => 'cumca144',
        ],
        23 => [
            'Sr No.' => 24,
            'First Name' => 'Anish',
            'Last Name' => 'Raheja',
            'Email ID' => 'D21MCA16025@cuchd.in',
            'Student Registration Number' => 'd21mca16025',
            'USERNAME' => 'd21mca16025',
            'PASSWORD' => 'cumca112',
        ],
        24 => [
            'Sr No.' => 25,
            'First Name' => 'Chainchal',
            'Last Name' => 'Rani',
            'Email ID' => 'D21MCA16026@cuchd.in',
            'Student Registration Number' => 'd21mca16026',
            'USERNAME' => 'd21mca16026',
            'PASSWORD' => 'cumca132',
        ],
        25 => [
            'Sr No.' => 26,
            'First Name' => 'Aarzoo',
            'Last Name' => 'Gaur',
            'Email ID' => 'D21MCA16027@cuchd.in',
            'Student Registration Number' => 'd21mca16027',
            'USERNAME' => 'd21mca16027',
            'PASSWORD' => 'cumca135',
        ],
        26 => [
            'Sr No.' => 27,
            'First Name' => 'Papan',
            'Last Name' => 'Chakraborty',
            'Email ID' => 'D21MCA16028@cuchd.in',
            'Student Registration Number' => 'd21mca16028',
            'USERNAME' => 'd21mca16028',
            'PASSWORD' => 'cumca108',
        ],
        27 => [
            'Sr No.' => 28,
            'First Name' => 'Vishwajit',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16029@cuchd.in',
            'Student Registration Number' => 'd21mca16029',
            'USERNAME' => 'd21mca16029',
            'PASSWORD' => 'cumca092',
        ],
        28 => [
            'Sr No.' => 29,
            'First Name' => 'Sonu',
            'Last Name' => 'Pal',
            'Email ID' => 'D21MCA16030@cuchd.in',
            'Student Registration Number' => 'd21mca16030',
            'USERNAME' => 'd21mca16030',
            'PASSWORD' => 'cumca150',
        ],
        29 => [
            'Sr No.' => 30,
            'First Name' => 'Sonu',
            'Last Name' => 'Raj',
            'Email ID' => 'D21MCA16031@cuchd.in',
            'Student Registration Number' => 'd21mca16031',
            'USERNAME' => 'd21mca16031',
            'PASSWORD' => 'cumca113',
        ],
        30 => [
            'Sr No.' => 31,
            'First Name' => 'Yash',
            'Last Name' => 'Aggarwal',
            'Email ID' => 'D21MCA16032@cuchd.in',
            'Student Registration Number' => 'd21mca16032',
            'USERNAME' => 'd21mca16032',
            'PASSWORD' => 'cumca141',
        ],
        31 => [
            'Sr No.' => 32,
            'First Name' => 'Madhuri',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16033@cuchd.in',
            'Student Registration Number' => 'd21mca16033',
            'USERNAME' => 'd21mca16033',
            'PASSWORD' => 'cumca115',
        ],
        32 => [
            'Sr No.' => 33,
            'First Name' => 'Gourav',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16034@cuchd.in',
            'Student Registration Number' => 'd21mca16034',
            'USERNAME' => 'd21mca16034',
            'PASSWORD' => 'cumca128',
        ],
        33 => [
            'Sr No.' => 34,
            'First Name' => 'Kanchan',
            'Last Name' => 'Yadav',
            'Email ID' => 'D21MCA16035@cuchd.in',
            'Student Registration Number' => 'd21mca16035',
            'USERNAME' => 'd21mca16035',
            'PASSWORD' => 'cumca103',
        ],
        34 => [
            'Sr No.' => 35,
            'First Name' => 'Sooryapriya',
            'Last Name' => 'T V',
            'Email ID' => 'D21MCA16036@cuchd.in',
            'Student Registration Number' => 'd21mca16036',
            'USERNAME' => 'd21mca16036',
            'PASSWORD' => 'cumca120',
        ],
        35 => [
            'Sr No.' => 36,
            'First Name' => 'Rahul',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16037@cuchd.in',
            'Student Registration Number' => 'd21mca16037',
            'USERNAME' => 'd21mca16037',
            'PASSWORD' => 'cumca118',
        ],
        36 => [
            'Sr No.' => 37,
            'First Name' => 'Vidya',
            'Last Name' => 'Ratan',
            'Email ID' => 'D21MCA16038@cuchd.in',
            'Student Registration Number' => 'd21mca16038',
            'USERNAME' => 'd21mca16038',
            'PASSWORD' => 'cumca151',
        ],
        37 => [
            'Sr No.' => 38,
            'First Name' => 'Simanchal',
            'Last Name' => 'Nayak',
            'Email ID' => 'D21MCA16039@cuchd.in',
            'Student Registration Number' => 'd21mca16039',
            'USERNAME' => 'd21mca16039',
            'PASSWORD' => 'cumca093',
        ],
        38 => [
            'Sr No.' => 39,
            'First Name' => 'Ankit',
            'Last Name' => 'Arora',
            'Email ID' => 'D21MCA16040@cuchd.in',
            'Student Registration Number' => 'd21mca16040',
            'USERNAME' => 'd21mca16040',
            'PASSWORD' => 'cumca142',
        ],
        39 => [
            'Sr No.' => 40,
            'First Name' => 'Maninder',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16041@cuchd.in',
            'Student Registration Number' => 'd21mca16041',
            'USERNAME' => 'd21mca16041',
            'PASSWORD' => 'cumca100',
        ],
        40 => [
            'Sr No.' => 41,
            'First Name' => 'Bhumika',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16042@cuchd.in',
            'Student Registration Number' => 'd21mca16042',
            'USERNAME' => 'd21mca16042',
            'PASSWORD' => 'cumca147',
        ],
        41 => [
            'Sr No.' => 42,
            'First Name' => 'Abhishek',
            'Last Name' => 'Srivastava',
            'Email ID' => 'D21MCA16043@cuchd.in',
            'Student Registration Number' => 'd21mca16043',
            'USERNAME' => 'd21mca16043',
            'PASSWORD' => 'cumca138',
        ],
        42 => [
            'Sr No.' => 43,
            'First Name' => 'Kanishk',
            'Last Name' => 'Aggarwal',
            'Email ID' => 'D21MCA16044@cuchd.in',
            'Student Registration Number' => 'd21mca16044',
            'USERNAME' => 'd21mca16044',
            'PASSWORD' => 'cumca095',
        ],
        43 => [
            'Sr No.' => 44,
            'First Name' => 'Sandeep',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16046@cuchd.in',
            'Student Registration Number' => 'd21mca16046',
            'USERNAME' => 'd21mca16046',
            'PASSWORD' => 'cumca121',
        ],
        44 => [
            'Sr No.' => 45,
            'First Name' => 'Vaishali',
            'Last Name' => 'Patel',
            'Email ID' => 'D21MCA16048@cuchd.in',
            'Student Registration Number' => 'd21mca16048',
            'USERNAME' => 'd21mca16048',
            'PASSWORD' => 'cumca101',
        ],
        45 => [
            'Sr No.' => 46,
            'First Name' => 'Shashwat',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16049@cuchd.in',
            'Student Registration Number' => 'd21mca16049',
            'USERNAME' => 'd21mca16049',
            'PASSWORD' => 'cumca106',
        ],
        46 => [
            'Sr No.' => 47,
            'First Name' => 'Gursimran',
            'Last Name' => 'Shah',
            'Email ID' => 'D21MCA16050@cuchd.in',
            'Student Registration Number' => 'd21mca16050',
            'USERNAME' => 'd21mca16050',
            'PASSWORD' => 'cumca131',
        ],
        47 => [
            'Sr No.' => 48,
            'First Name' => 'Udit',
            'Last Name' => 'Arora',
            'Email ID' => 'D21MCA16051@cuchd.in',
            'Student Registration Number' => 'd21mca16051',
            'USERNAME' => 'd21mca16051',
            'PASSWORD' => 'cumca122',
        ],
        48 => [
            'Sr No.' => 49,
            'First Name' => 'Shivam',
            'Last Name' => 'Tyagi',
            'Email ID' => 'D21MCA16052@cuchd.in',
            'Student Registration Number' => 'd21mca16052',
            'USERNAME' => 'd21mca16052',
            'PASSWORD' => 'cumca119',
        ],
        49 => [
            'Sr No.' => 50,
            'First Name' => 'twinkle',
            'Last Name' => 'agrawal',
            'Email ID' => 'D21MCA16053@cuchd.in',
            'Student Registration Number' => 'd21mca16053',
            'USERNAME' => 'd21mca16053',
            'PASSWORD' => 'cumca109',
        ],
        50 => [
            'Sr No.' => 51,
            'First Name' => 'Yogesh',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16054@cuchd.in',
            'Student Registration Number' => 'd21mca16054',
            'USERNAME' => 'd21mca16054',
            'PASSWORD' => 'cumca123',
        ],
        51 => [
            'Sr No.' => 52,
            'First Name' => 'Anurag',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16055@cuchd.in',
            'Student Registration Number' => 'd21mca16055',
            'USERNAME' => 'd21mca16055',
            'PASSWORD' => 'cumca094',
        ],
        52 => [
            'Sr No.' => 53,
            'First Name' => 'Bhoomika',
            'Last Name' => 'Behl',
            'Email ID' => 'D21MCA16056@cuchd.in',
            'Student Registration Number' => 'd21mca16056',
            'USERNAME' => 'd21mca16056',
            'PASSWORD' => 'cumca096',
        ],
        53 => [
            'Sr No.' => 54,
            'First Name' => 'Leeza',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16057@cuchd.in',
            'Student Registration Number' => 'd21mca16057',
            'USERNAME' => 'd21mca16057',
            'PASSWORD' => 'cumca114',
        ],
        54 => [
            'Sr No.' => 55,
            'First Name' => 'Jyotika',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16059@cuchd.in',
            'Student Registration Number' => 'd21mca16059',
            'USERNAME' => 'd21mca16059',
            'PASSWORD' => 'cumca097',
        ],
        55 => [
            'Sr No.' => 56,
            'First Name' => 'Devesh',
            'Last Name' => 'Chattani',
            'Email ID' => 'D21MCA16060@cuchd.in',
            'Student Registration Number' => 'd21mca16060',
            'USERNAME' => 'd21mca16060',
            'PASSWORD' => 'cumca098',
        ],
        56 => [
            'Sr No.' => 57,
            'First Name' => 'Sukhleen',
            'Last Name' => 'Kaur',
            'Email ID' => 'D21MCA16061@cuchd.in',
            'Student Registration Number' => 'd21mca16061',
            'USERNAME' => 'd21mca16061',
            'PASSWORD' => 'cumca125',
        ],
        57 => [
            'Sr No.' => 58,
            'First Name' => 'Vanshika',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16062@cuchd.in',
            'Student Registration Number' => 'd21mca16062',
            'USERNAME' => 'd21mca16062',
            'PASSWORD' => 'cumca133',
        ],
        58 => [
            'Sr No.' => 59,
            'First Name' => 'Muskan',
            'Last Name' => 'Rajput',
            'Email ID' => 'D21MCA16064@cuchd.in',
            'Student Registration Number' => 'd21mca16064',
            'USERNAME' => 'd21mca16064',
            'PASSWORD' => 'cumca124',
        ],
        59 => [
            'Sr No.' => 60,
            'First Name' => 'Lokajita',
            'Last Name' => 'Saravanan',
            'Email ID' => 'D21MCA16065@cuchd.in',
            'Student Registration Number' => 'd21mca16065',
            'USERNAME' => 'd21mca16065',
            'PASSWORD' => 'cumca104',
        ],
        60 => [
            'Sr No.' => 61,
            'First Name' => 'Mayank',
            'Last Name' => 'Joshi',
            'Email ID' => 'D21MCA16066@cuchd.in',
            'Student Registration Number' => 'd21mca16066',
            'USERNAME' => 'd21mca16066',
            'PASSWORD' => 'cumca099',
        ],
        61 => [
            'Sr No.' => 62,
            'First Name' => 'Ali',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16067@cuchd.in',
            'Student Registration Number' => 'd21mca16067',
            'USERNAME' => 'd21mca16067',
            'PASSWORD' => 'cumca089',
        ],
        62 => [
            'Sr No.' => 63,
            'First Name' => 'Ahamed',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16068@cuchd.in',
            'Student Registration Number' => 'd21mca16068',
            'USERNAME' => 'd21mca16068',
            'PASSWORD' => 'cumca091',
        ],
        63 => [
            'Sr No.' => 64,
            'First Name' => 'Mainak',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16069@cuchd.in',
            'Student Registration Number' => 'd21mca16069',
            'USERNAME' => 'd21mca16069',
            'PASSWORD' => 'cumca090',
        ],
        64 => [
            'Sr No.' => 65,
            'First Name' => 'Kunal',
            'Last Name' => 'Sinha',
            'Email ID' => 'D21MCA16071@cuchd.in',
            'Student Registration Number' => 'd21mca16071',
            'USERNAME' => 'd21mca16071',
            'PASSWORD' => 'cumca068',
        ],
        65 => [
            'Sr No.' => 66,
            'First Name' => 'Jain',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16072@cuchd.in',
            'Student Registration Number' => 'd21mca16072',
            'USERNAME' => 'd21mca16072',
            'PASSWORD' => 'cumca088',
        ],
        66 => [
            'Sr No.' => 67,
            'First Name' => 'Ashish',
            'Last Name' => 'Shishodia',
            'Email ID' => 'D21MCA16073@cuchd.in',
            'Student Registration Number' => 'd21mca16073',
            'USERNAME' => 'd21mca16073',
            'PASSWORD' => 'cumca086',
        ],
        67 => [
            'Sr No.' => 68,
            'First Name' => 'Srinivas',
            'Last Name' => 'Krovvidi',
            'Email ID' => 'D21MCA16075@cuchd.in',
            'Student Registration Number' => 'd21mca16075',
            'USERNAME' => 'd21mca16075',
            'PASSWORD' => 'cumca055',
        ],
        68 => [
            'Sr No.' => 69,
            'First Name' => 'Gautam',
            'Last Name' => 'Das',
            'Email ID' => 'D21MCA16076@cuchd.in',
            'Student Registration Number' => 'd21mca16076',
            'USERNAME' => 'd21mca16076',
            'PASSWORD' => 'cumca087',
        ],
        69 => [
            'Sr No.' => 70,
            'First Name' => 'Indrani',
            'Last Name' => 'Ghosh',
            'Email ID' => 'D21MCA16077@cuchd.in',
            'Student Registration Number' => 'd21mca16077',
            'USERNAME' => 'd21mca16077',
            'PASSWORD' => 'cumca084',
        ],
        70 => [
            'Sr No.' => 71,
            'First Name' => 'Shruti',
            'Last Name' => 'Bhardwaj',
            'Email ID' => 'D21MCA16078@cuchd.in',
            'Student Registration Number' => 'd21mca16078',
            'USERNAME' => 'd21mca16078',
            'PASSWORD' => 'cumca067',
        ],
        71 => [
            'Sr No.' => 72,
            'First Name' => 'Hitesh',
            'Last Name' => 'Goswami',
            'Email ID' => 'D21MCA16079@cuchd.in',
            'Student Registration Number' => 'd21mca16079',
            'USERNAME' => 'd21mca16079',
            'PASSWORD' => 'cumca065',
        ],
        72 => [
            'Sr No.' => 73,
            'First Name' => 'Bediya',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16080@cuchd.in',
            'Student Registration Number' => 'd21mca16080',
            'USERNAME' => 'd21mca16080',
            'PASSWORD' => 'cumca085',
        ],
        73 => [
            'Sr No.' => 74,
            'First Name' => 'Jeewan',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16081@cuchd.in',
            'Student Registration Number' => 'd21mca16081',
            'USERNAME' => 'd21mca16081',
            'PASSWORD' => 'cumca083',
        ],
        74 => [
            'Sr No.' => 75,
            'First Name' => 'Rakesh',
            'Last Name' => 'Shejwalkar',
            'Email ID' => 'D21MCA16082@cuchd.in',
            'Student Registration Number' => 'd21mca16082',
            'USERNAME' => 'd21mca16082',
            'PASSWORD' => 'cumca081',
        ],
        75 => [
            'Sr No.' => 76,
            'First Name' => 'Sanjay',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16083@cuchd.in',
            'Student Registration Number' => 'd21mca16083',
            'USERNAME' => 'd21mca16083',
            'PASSWORD' => 'cumca064',
        ],
        76 => [
            'Sr No.' => 77,
            'First Name' => 'Zinathasmee',
            'Last Name' => 'Sayyad',
            'Email ID' => 'D21MCA16084@cuchd.in',
            'Student Registration Number' => 'd21mca16084',
            'USERNAME' => 'd21mca16084',
            'PASSWORD' => 'cumca082',
        ],
        77 => [
            'Sr No.' => 78,
            'First Name' => 'K',
            'Last Name' => 'Rajasekhara',
            'Email ID' => 'D21MCA16085@cuchd.in',
            'Student Registration Number' => 'd21mca16085',
            'USERNAME' => 'd21mca16085',
            'PASSWORD' => 'cumca077',
        ],
        78 => [
            'Sr No.' => 79,
            'First Name' => 'Ravinder',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16086@cuchd.in',
            'Student Registration Number' => 'd21mca16086',
            'USERNAME' => 'd21mca16086',
            'PASSWORD' => 'cumca069',
        ],
        79 => [
            'Sr No.' => 80,
            'First Name' => 'Bhuvnesh',
            'Last Name' => 'Sukhija',
            'Email ID' => 'D21MCA16087@cuchd.in',
            'Student Registration Number' => 'd21mca16087',
            'USERNAME' => 'd21mca16087',
            'PASSWORD' => 'cumca073',
        ],
        80 => [
            'Sr No.' => 81,
            'First Name' => 'Aameen',
            'Last Name' => 'Lakhanpal',
            'Email ID' => 'D21MCA16088@cuchd.in',
            'Student Registration Number' => 'd21mca16088',
            'USERNAME' => 'd21mca16088',
            'PASSWORD' => 'cumca063',
        ],
        81 => [
            'Sr No.' => 82,
            'First Name' => 'Dhruv',
            'Last Name' => 'Bhatt',
            'Email ID' => 'D21MCA16089@cuchd.in',
            'Student Registration Number' => 'd21mca16089',
            'USERNAME' => 'd21mca16089',
            'PASSWORD' => 'cumca079',
        ],
        82 => [
            'Sr No.' => 83,
            'First Name' => 'Pallavi',
            'Last Name' => 'Kar',
            'Email ID' => 'D21MCA16090@cuchd.in',
            'Student Registration Number' => 'd21mca16090',
            'USERNAME' => 'd21mca16090',
            'PASSWORD' => 'cumca080',
        ],
        83 => [
            'Sr No.' => 84,
            'First Name' => 'Gaurav',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16091@cuchd.in',
            'Student Registration Number' => 'd21mca16091',
            'USERNAME' => 'd21mca16091',
            'PASSWORD' => 'cumca078',
        ],
        84 => [
            'Sr No.' => 85,
            'First Name' => 'Subhash',
            'Last Name' => 'Chand',
            'Email ID' => 'D21MCA16092@cuchd.in',
            'Student Registration Number' => 'd21mca16092',
            'USERNAME' => 'd21mca16092',
            'PASSWORD' => 'cumca054',
        ],
        85 => [
            'Sr No.' => 86,
            'First Name' => 'Anand',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16093@cuchd.in',
            'Student Registration Number' => 'd21mca16093',
            'USERNAME' => 'd21mca16093',
            'PASSWORD' => 'cumca053',
        ],
        86 => [
            'Sr No.' => 87,
            'First Name' => 'Garima',
            'Last Name' => 'Chhikara',
            'Email ID' => 'D21MCA16094@cuchd.in',
            'Student Registration Number' => 'd21mca16094',
            'USERNAME' => 'd21mca16094',
            'PASSWORD' => 'cumca056',
        ],
        87 => [
            'Sr No.' => 88,
            'First Name' => 'Ayush',
            'Last Name' => 'Mishra',
            'Email ID' => 'D21MCA16095@cuchd.in',
            'Student Registration Number' => 'd21mca16095',
            'USERNAME' => 'd21mca16095',
            'PASSWORD' => 'cumca060',
        ],
        88 => [
            'Sr No.' => 89,
            'First Name' => 'Rajesh',
            'Last Name' => 'Dubey',
            'Email ID' => 'D21MCA16096@cuchd.in',
            'Student Registration Number' => 'd21mca16096',
            'USERNAME' => 'd21mca16096',
            'PASSWORD' => 'cumca074',
        ],
        89 => [
            'Sr No.' => 90,
            'First Name' => 'Prakriti',
            'Last Name' => 'Anand',
            'Email ID' => 'D21MCA16097@cuchd.in',
            'Student Registration Number' => 'd21mca16097',
            'USERNAME' => 'd21mca16097',
            'PASSWORD' => 'cumca076',
        ],
        90 => [
            'Sr No.' => 91,
            'First Name' => 'Rupesh',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16098@cuchd.in',
            'Student Registration Number' => 'd21mca16098',
            'USERNAME' => 'd21mca16098',
            'PASSWORD' => 'cumca066',
        ],
        91 => [
            'Sr No.' => 92,
            'First Name' => 'Sabhadiya',
            'Last Name' => 'Ankitkumar',
            'Email ID' => 'D21MCA16100@cuchd.in',
            'Student Registration Number' => 'd21mca16100',
            'USERNAME' => 'd21mca16100',
            'PASSWORD' => 'cumca062',
        ],
        92 => [
            'Sr No.' => 93,
            'First Name' => 'Harpreet',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16101@cuchd.in',
            'Student Registration Number' => 'd21mca16101',
            'USERNAME' => 'd21mca16101',
            'PASSWORD' => 'cumca061',
        ],
        93 => [
            'Sr No.' => 94,
            'First Name' => 'Sunny',
            'Last Name' => 'Bhardwaj',
            'Email ID' => 'D21MCA16102@cuchd.in',
            'Student Registration Number' => 'd21mca16102',
            'USERNAME' => 'd21mca16102',
            'PASSWORD' => 'cumca042',
        ],
        94 => [
            'Sr No.' => 95,
            'First Name' => 'Himani',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16103@cuchd.in',
            'Student Registration Number' => 'd21mca16103',
            'USERNAME' => 'd21mca16103',
            'PASSWORD' => 'cumca050',
        ],
        95 => [
            'Sr No.' => 96,
            'First Name' => 'Pragya',
            'Last Name' => 'Mishra',
            'Email ID' => 'D21MCA16104@cuchd.in',
            'Student Registration Number' => 'd21mca16104',
            'USERNAME' => 'd21mca16104',
            'PASSWORD' => 'cumca075',
        ],
        96 => [
            'Sr No.' => 97,
            'First Name' => 'Ritika',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16105@cuchd.in',
            'Student Registration Number' => 'd21mca16105',
            'USERNAME' => 'd21mca16105',
            'PASSWORD' => 'cumca057',
        ],
        97 => [
            'Sr No.' => 98,
            'First Name' => 'Jai',
            'Last Name' => 'Sahni',
            'Email ID' => 'D21MCA16106@cuchd.in',
            'Student Registration Number' => 'd21mca16106',
            'USERNAME' => 'd21mca16106',
            'PASSWORD' => 'cumca072',
        ],
        98 => [
            'Sr No.' => 99,
            'First Name' => 'Shazan',
            'Last Name' => 'Askari',
            'Email ID' => 'D21MCA16107@cuchd.in',
            'Student Registration Number' => 'd21mca16107',
            'USERNAME' => 'd21mca16107',
            'PASSWORD' => 'cumca071',
        ],
        99 => [
            'Sr No.' => 100,
            'First Name' => 'Tripti',
            'Last Name' => 'Suman',
            'Email ID' => 'D21MCA16108@cuchd.in',
            'Student Registration Number' => 'd21mca16108',
            'USERNAME' => 'd21mca16108',
            'PASSWORD' => 'cumca070',
        ],
        100 => [
            'Sr No.' => 101,
            'First Name' => 'Shivam',
            'Last Name' => 'Singla',
            'Email ID' => 'D21MCA16109@cuchd.in',
            'Student Registration Number' => 'd21mca16109',
            'USERNAME' => 'd21mca16109',
            'PASSWORD' => 'cumca059',
        ],
        101 => [
            'Sr No.' => 102,
            'First Name' => 'Bhuvan',
            'Last Name' => 'Bajaj',
            'Email ID' => 'D21MCA16110@cuchd.in',
            'Student Registration Number' => 'd21mca16110',
            'USERNAME' => 'd21mca16110',
            'PASSWORD' => 'cumca058',
        ],
        102 => [
            'Sr No.' => 103,
            'First Name' => 'Saurav',
            'Last Name' => 'Prasad',
            'Email ID' => 'D21MCA16111@cuchd.in',
            'Student Registration Number' => 'd21mca16111',
            'USERNAME' => 'd21mca16111',
            'PASSWORD' => 'cumca046',
        ],
        103 => [
            'Sr No.' => 104,
            'First Name' => 'Ginjupalli',
            'Last Name' => 'Neha',
            'Email ID' => 'D21MCA16112@cuchd.in',
            'Student Registration Number' => 'd21mca16112',
            'USERNAME' => 'd21mca16112',
            'PASSWORD' => 'cumca039',
        ],
        104 => [
            'Sr No.' => 105,
            'First Name' => 'Shivam',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16113@cuchd.in',
            'Student Registration Number' => 'd21mca16113',
            'USERNAME' => 'd21mca16113',
            'PASSWORD' => 'cumca040',
        ],
        105 => [
            'Sr No.' => 106,
            'First Name' => 'Jyotiprakash',
            'Last Name' => 'Rout',
            'Email ID' => 'D21MCA16115@cuchd.in',
            'Student Registration Number' => 'd21mca16115',
            'USERNAME' => 'd21mca16115',
            'PASSWORD' => 'cumca047',
        ],
        106 => [
            'Sr No.' => 107,
            'First Name' => 'Subhadip',
            'Last Name' => 'Mitra',
            'Email ID' => 'D21MCA16116@cuchd.in',
            'Student Registration Number' => 'd21mca16116',
            'USERNAME' => 'd21mca16116',
            'PASSWORD' => 'cumca045',
        ],
        107 => [
            'Sr No.' => 108,
            'First Name' => 'Raj',
            'Last Name' => 'Gaurav',
            'Email ID' => 'D21MCA16117@cuchd.in',
            'Student Registration Number' => 'd21mca16117',
            'USERNAME' => 'd21mca16117',
            'PASSWORD' => 'cumca049',
        ],
        108 => [
            'Sr No.' => 109,
            'First Name' => 'Divya',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16118@cuchd.in',
            'Student Registration Number' => 'd21mca16118',
            'USERNAME' => 'd21mca16118',
            'PASSWORD' => 'cumca038',
        ],
        109 => [
            'Sr No.' => 110,
            'First Name' => 'Naveen',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16119@cuchd.in',
            'Student Registration Number' => 'd21mca16119',
            'USERNAME' => 'd21mca16119',
            'PASSWORD' => 'cumca041',
        ],
        110 => [
            'Sr No.' => 111,
            'First Name' => 'Ankit',
            'Last Name' => 'Jangid',
            'Email ID' => 'D21MCA16120@cuchd.in',
            'Student Registration Number' => 'd21mca16120',
            'USERNAME' => 'd21mca16120',
            'PASSWORD' => 'cumca036',
        ],
        111 => [
            'Sr No.' => 112,
            'First Name' => 'Yadav',
            'Last Name' => 'Pooja',
            'Email ID' => 'D21MCA16121@cuchd.in',
            'Student Registration Number' => 'd21mca16121',
            'USERNAME' => 'd21mca16121',
            'PASSWORD' => 'cumca043',
        ],
        112 => [
            'Sr No.' => 113,
            'First Name' => 'Manpreet',
            'Last Name' => 'Kaur',
            'Email ID' => 'D21MCA16122@cuchd.in',
            'Student Registration Number' => 'd21mca16122',
            'USERNAME' => 'd21mca16122',
            'PASSWORD' => 'cumca044',
        ],
        113 => [
            'Sr No.' => 114,
            'First Name' => 'Renu',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16123@cuchd.in',
            'Student Registration Number' => 'd21mca16123',
            'USERNAME' => 'd21mca16123',
            'PASSWORD' => 'cumca051',
        ],
        114 => [
            'Sr No.' => 115,
            'First Name' => 'Abhilasha',
            'Last Name' => 'Kumari',
            'Email ID' => 'D21MCA16124@cuchd.in',
            'Student Registration Number' => 'd21mca16124',
            'USERNAME' => 'd21mca16124',
            'PASSWORD' => 'cumca048',
        ],
        115 => [
            'Sr No.' => 116,
            'First Name' => 'Tinku',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16125@cuchd.in',
            'Student Registration Number' => 'd21mca16125',
            'USERNAME' => 'd21mca16125',
            'PASSWORD' => 'cumca035',
        ],
        116 => [
            'Sr No.' => 117,
            'First Name' => 'Shruti',
            'Last Name' => 'Mondeala',
            'Email ID' => 'D21MCA16126@cuchd.in',
            'Student Registration Number' => 'd21mca16126',
            'USERNAME' => 'd21mca16126',
            'PASSWORD' => 'cumca037',
        ],
        117 => [
            'Sr No.' => 118,
            'First Name' => 'Deepika',
            'Last Name' => 'Rathee',
            'Email ID' => 'D21MCA16129@cuchd.in',
            'Student Registration Number' => 'd21mca16129',
            'USERNAME' => 'd21mca16129',
            'PASSWORD' => 'cumca028',
        ],
        118 => [
            'Sr No.' => 119,
            'First Name' => 'Anu',
            'Last Name' => 'Bala',
            'Email ID' => 'D21MCA16130@cuchd.in',
            'Student Registration Number' => 'd21mca16130',
            'USERNAME' => 'd21mca16130',
            'PASSWORD' => 'cumca033',
        ],
        119 => [
            'Sr No.' => 120,
            'First Name' => 'Dipanjoy',
            'Last Name' => 'Deb',
            'Email ID' => 'D21MCA16131@cuchd.in',
            'Student Registration Number' => 'd21mca16131',
            'USERNAME' => 'd21mca16131',
            'PASSWORD' => 'cumca032',
        ],
        120 => [
            'Sr No.' => 121,
            'First Name' => 'Anjali',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16132@cuchd.in',
            'Student Registration Number' => 'd21mca16132',
            'USERNAME' => 'd21mca16132',
            'PASSWORD' => 'cumca031',
        ],
        121 => [
            'Sr No.' => 122,
            'First Name' => 'Parminder',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16133@cuchd.in',
            'Student Registration Number' => 'd21mca16133',
            'USERNAME' => 'd21mca16133',
            'PASSWORD' => 'cumca027',
        ],
        122 => [
            'Sr No.' => 123,
            'First Name' => 'Sanjay',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16134@cuchd.in',
            'Student Registration Number' => 'd21mca16134',
            'USERNAME' => 'd21mca16134',
            'PASSWORD' => 'cumca029',
        ],
        123 => [
            'Sr No.' => 124,
            'First Name' => 'Manpreet',
            'Last Name' => 'Kaur',
            'Email ID' => 'D21MCA16135@cuchd.in',
            'Student Registration Number' => 'd21mca16135',
            'USERNAME' => 'd21mca16135',
            'PASSWORD' => 'cumca030',
        ],
        124 => [
            'Sr No.' => 125,
            'First Name' => 'Deepshikha',
            'Last Name' => 'Ghosh',
            'Email ID' => 'D21MCA16136@cuchd.in',
            'Student Registration Number' => 'd21mca16136',
            'USERNAME' => 'd21mca16136',
            'PASSWORD' => 'cumca034',
        ],
        125 => [
            'Sr No.' => 126,
            'First Name' => 'Sunil',
            'Last Name' => 'Jaisinghani',
            'Email ID' => 'D21MCA16139@cuchd.in',
            'Student Registration Number' => 'd21mca16139',
            'USERNAME' => 'd21mca16139',
            'PASSWORD' => 'cumca016',
        ],
        126 => [
            'Sr No.' => 127,
            'First Name' => 'Mayank',
            'Last Name' => 'Pratap',
            'Email ID' => 'D21MCA16140@cuchd.in',
            'Student Registration Number' => 'd21mca16140',
            'USERNAME' => 'd21mca16140',
            'PASSWORD' => 'cumca018',
        ],
        127 => [
            'Sr No.' => 128,
            'First Name' => 'Sahil',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16141@cuchd.in',
            'Student Registration Number' => 'd21mca16141',
            'USERNAME' => 'd21mca16141',
            'PASSWORD' => 'cumca009',
        ],
        128 => [
            'Sr No.' => 129,
            'First Name' => 'Vikram',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16142@cuchd.in',
            'Student Registration Number' => 'd21mca16142',
            'USERNAME' => 'd21mca16142',
            'PASSWORD' => 'cumca008',
        ],
        129 => [
            'Sr No.' => 130,
            'First Name' => 'Pankaj',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16143@cuchd.in',
            'Student Registration Number' => 'd21mca16143',
            'USERNAME' => 'd21mca16143',
            'PASSWORD' => 'cumca007',
        ],
        130 => [
            'Sr No.' => 131,
            'First Name' => 'Anand',
            'Last Name' => 'Vardhan',
            'Email ID' => 'D21MCA16144@cuchd.in',
            'Student Registration Number' => 'd21mca16144',
            'USERNAME' => 'd21mca16144',
            'PASSWORD' => 'cumca005',
        ],
        131 => [
            'Sr No.' => 132,
            'First Name' => 'Yash',
            'Last Name' => 'Gupta',
            'Email ID' => 'D21MCA16145@cuchd.in',
            'Student Registration Number' => 'd21mca16145',
            'USERNAME' => 'd21mca16145',
            'PASSWORD' => 'cumca025',
        ],
        132 => [
            'Sr No.' => 133,
            'First Name' => 'Mohammad',
            'Last Name' => 'Raheemullah',
            'Email ID' => 'D21MCA16146@cuchd.in',
            'Student Registration Number' => 'd21mca16146',
            'USERNAME' => 'd21mca16146',
            'PASSWORD' => 'cumca013',
        ],
        133 => [
            'Sr No.' => 134,
            'First Name' => 'Barsha',
            'Last Name' => 'Mohapatra',
            'Email ID' => 'D21MCA16148@cuchd.in',
            'Student Registration Number' => 'd21mca16148',
            'USERNAME' => 'd21mca16148',
            'PASSWORD' => 'cumca026',
        ],
        134 => [
            'Sr No.' => 135,
            'First Name' => 'Vishal',
            'Last Name' => 'Kapoor',
            'Email ID' => 'D21MCA16149@cuchd.in',
            'Student Registration Number' => 'd21mca16149',
            'USERNAME' => 'd21mca16149',
            'PASSWORD' => 'cumca017',
        ],
        135 => [
            'Sr No.' => 136,
            'First Name' => 'Ashutosh',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16150@cuchd.in',
            'Student Registration Number' => 'd21mca16150',
            'USERNAME' => 'd21mca16150',
            'PASSWORD' => 'cumca010',
        ],
        136 => [
            'Sr No.' => 137,
            'First Name' => 'D',
            'Last Name' => 'Akhil',
            'Email ID' => 'D21MCA16151@cuchd.in',
            'Student Registration Number' => 'd21mca16151',
            'USERNAME' => 'd21mca16151',
            'PASSWORD' => 'cumca022',
        ],
        137 => [
            'Sr No.' => 138,
            'First Name' => 'Anshul',
            'Last Name' => 'Siwach',
            'Email ID' => 'D21MCA16152@cuchd.in',
            'Student Registration Number' => 'd21mca16152',
            'USERNAME' => 'd21mca16152',
            'PASSWORD' => 'cumca019',
        ],
        138 => [
            'Sr No.' => 139,
            'First Name' => 'Abhishek',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16153@cuchd.in',
            'Student Registration Number' => 'd21mca16153',
            'USERNAME' => 'd21mca16153',
            'PASSWORD' => 'cumca012',
        ],
        139 => [
            'Sr No.' => 140,
            'First Name' => 'Pooja',
            'Last Name' => 'Batra',
            'Email ID' => 'D21MCA16154@cuchd.in',
            'Student Registration Number' => 'd21mca16154',
            'USERNAME' => 'd21mca16154',
            'PASSWORD' => 'cumca004',
        ],
        140 => [
            'Sr No.' => 141,
            'First Name' => 'Ankit',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16155@cuchd.in',
            'Student Registration Number' => 'd21mca16155',
            'USERNAME' => 'd21mca16155',
            'PASSWORD' => 'cumca023',
        ],
        141 => [
            'Sr No.' => 142,
            'First Name' => 'Hitesh',
            'Last Name' => '.',
            'Email ID' => 'D21MCA16156@cuchd.in',
            'Student Registration Number' => 'd21mca16156',
            'USERNAME' => 'd21mca16156',
            'PASSWORD' => 'cumca011',
        ],
        142 => [
            'Sr No.' => 143,
            'First Name' => 'Aman',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16157@cuchd.in',
            'Student Registration Number' => 'd21mca16157',
            'USERNAME' => 'd21mca16157',
            'PASSWORD' => 'cumca024',
        ],
        143 => [
            'Sr No.' => 144,
            'First Name' => 'Gaurav',
            'Last Name' => 'Batra',
            'Email ID' => 'D21MCA16158@cuchd.in',
            'Student Registration Number' => 'd21mca16158',
            'USERNAME' => 'd21mca16158',
            'PASSWORD' => 'cumca006',
        ],
        144 => [
            'Sr No.' => 145,
            'First Name' => 'Surbhi',
            'Last Name' => 'Sharma',
            'Email ID' => 'D21MCA16159@cuchd.in',
            'Student Registration Number' => 'd21mca16159',
            'USERNAME' => 'd21mca16159',
            'PASSWORD' => 'cumca014',
        ],
        145 => [
            'Sr No.' => 146,
            'First Name' => 'Kavya',
            'Last Name' => 'Agarwal',
            'Email ID' => 'D21MCA16160@cuchd.in',
            'Student Registration Number' => 'd21mca16160',
            'USERNAME' => 'd21mca16160',
            'PASSWORD' => 'cumca015',
        ],
        146 => [
            'Sr No.' => 147,
            'First Name' => 'Ashish',
            'Last Name' => 'Labh',
            'Email ID' => 'D21MCA16161@cuchd.in',
            'Student Registration Number' => 'd21mca16161',
            'USERNAME' => 'd21mca16161',
            'PASSWORD' => 'cumca003',
        ],
        147 => [
            'Sr No.' => 148,
            'First Name' => 'Rohan',
            'Last Name' => 'Singh',
            'Email ID' => 'D21MCA16162@cuchd.in',
            'Student Registration Number' => 'd21mca16162',
            'USERNAME' => 'd21mca16162',
            'PASSWORD' => 'cumca021',
        ],
        148 => [
            'Sr No.' => 149,
            'First Name' => 'Krishno',
            'Last Name' => 'Ghosh',
            'Email ID' => 'D21MCA16163@cuchd.in',
            'Student Registration Number' => 'd21mca16163',
            'USERNAME' => 'd21mca16163',
            'PASSWORD' => 'cumca020',
        ],
        149 => [
            'Sr No.' => 150,
            'First Name' => 'TILAKDHARI',
            'Last Name' => 'SINGH',
            'Email ID' => 'D21MCA16164@cuchd.in',
            'Student Registration Number' => 'd21mca16164',
            'USERNAME' => 'd21mca16164',
            'PASSWORD' => 'cumca052',
        ],
        150 => [
            'Sr No.' => 151,
            'First Name' => 'Chitransh',
            'Last Name' => 'Mathur',
            'Email ID' => 'D21MCA16165@cuchd.in',
            'Student Registration Number' => 'd21mca16165',
            'USERNAME' => 'd21mca16165',
            'PASSWORD' => 'cumca002',
        ],
        151 => [
            'Sr No.' => 152,
            'First Name' => 'Baijayanti',
            'Last Name' => 'Das',
            'Email ID' => 'D21MCA16166@cuchd.in',
            'Student Registration Number' => 'd21mca16166',
            'USERNAME' => 'd21mca16166',
            'PASSWORD' => 'cumca153',
        ],
        152 => [
            'Sr No.' => 153,
            'First Name' => 'Chandan',
            'Last Name' => 'Kumar',
            'Email ID' => 'D21MCA16167@cuchd.in',
            'Student Registration Number' => 'd21mca16167',
            'USERNAME' => 'd21mca16167',
            'PASSWORD' => 'cumca154',
        ],
    ]
];
